"use client";
import { useState } from "react";
import { Copy, Download, FileText, Image, Check } from "lucide-react";
import { toast } from "sonner";
import type { CalculateResponse } from "@/types/math";

interface Props {
  result: CalculateResponse;
}

export function ExportOptions({ result }: Props) {
  const [copied, setCopied] = useState<string | null>(null);

  const copyToClipboard = async (text: string, label: string) => {
    await navigator.clipboard.writeText(text);
    setCopied(label);
    toast.success(`Copied ${label} to clipboard`);
    setTimeout(() => setCopied(null), 2000);
  };

  const exportLatex = () => {
    const latex = `\\[
${result.result_latex || result.result}
\\]`;
    copyToClipboard(latex, "LaTeX");
  };

  const exportPDF = async () => {
    try {
      const { default: jsPDF } = await import("jspdf");
      const doc = new jsPDF();

      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text("Universal Scientific Calculator", 20, 25);

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 100, 100);
      doc.text(`Operation: ${result.operation}`, 20, 38);
      doc.text(`Input: ${result.input}`, 20, 48);

      doc.setDrawColor(230, 230, 230);
      doc.line(20, 55, 190, 55);

      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 0, 0);
      doc.text("Result:", 20, 68);

      doc.setFontSize(12);
      doc.setFont("courier", "normal");
      const resultText = result.result || "No result";
      const splitResult = doc.splitTextToSize(resultText, 170);
      doc.text(splitResult, 20, 78);

      let y = 78 + splitResult.length * 7 + 15;

      if (result.steps && result.steps.length > 0) {
        doc.setFontSize(13);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(0, 0, 0);
        doc.text("Step-by-step Solution:", 20, y);
        y += 10;

        result.steps.forEach((step) => {
          if (y > 270) {
            doc.addPage();
            y = 25;
          }
          doc.setFontSize(10);
          doc.setFont("helvetica", "bold");
          doc.setTextColor(37, 99, 235);
          doc.text(`Step ${step.index}: ${step.description}`, 20, y);
          y += 7;

          if (step.expression) {
            doc.setFont("courier", "normal");
            doc.setTextColor(50, 50, 50);
            const splitExpr = doc.splitTextToSize(step.expression, 165);
            doc.text(splitExpr, 25, y);
            y += splitExpr.length * 6 + 5;
          }
        });
      }

      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated by Universal Scientific Calculator · ${new Date().toLocaleDateString()}`, 20, 285);

      doc.save(`calculation-${result.operation}-${Date.now()}.pdf`);
      toast.success("PDF exported");
    } catch (e) {
      toast.error("PDF export failed");
    }
  };

  return (
    <div className="flex flex-wrap gap-2">
      <button
        onClick={() => copyToClipboard(result.result || "", "Result")}
        className="inline-flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 border border-gray-200 rounded-lg text-gray-600 hover:bg-gray-50 transition-colors"
      >
        {copied === "Result" ? <Check className="w-3.5 h-3.5 text-green-600" /> : <Copy className="w-3.5 h-3.5" />}
        Copy Result
      </button>

      <button
        onClick={exportLatex}
        className="inline-flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 border border-gray-200 rounded-lg text-gray-600 hover:bg-gray-50 transition-colors"
      >
        {copied === "LaTeX" ? <Check className="w-3.5 h-3.5 text-green-600" /> : <Copy className="w-3.5 h-3.5" />}
        Copy LaTeX
      </button>

      <button
        onClick={exportPDF}
        className="inline-flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 border border-gray-200 rounded-lg text-gray-600 hover:bg-gray-50 transition-colors"
      >
        <FileText className="w-3.5 h-3.5" />
        Export PDF
      </button>
    </div>
  );
}
